author:
  email: "santos.lopez@galileo.edu"
  url: "https://www.lacadenagt.com"
excerpt_separator: <!--more-->
baseurl: ""
markdown: kramdown
permalink: /posts/:year/:month/:day/:title
plugins:
  - jekyll-feed
